version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: "/usr/src/app/bootstrap.sh"
    volumes:
      - ./config:/usr/src/app/config/
      - ./instance:/usr/src/app/instance/
      - ./project:/usr/src/app/project/
      - ./manage.py:/usr/src/app/manage.py
    ports:
     - "5000:5000"
