version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: "/app/bootstrap.sh"
    volumes:
      - ./config:/app/config/
      - ./instance:/app/instance/
      - ./app:/app/project/
      - ./autoapp.py:/app/manage.py
    ports:
     - "5000:5000"
