# Using lightweight alpine image
FROM python:3.6-alpine

# Installing packages
RUN apk update && apk add --no-cache bash
RUN pip install --no-cache-dir pipenv

# Defining working directory and adding source code
WORKDIR /usr/src/app
COPY Pipfile Pipfile.lock bootstrap.sh /usr/src/app/

# Install API dependencies
RUN pipenv install

EXPOSE 5000